version: '3.1'

services:
  scheduler:
    build:
      context: .
      dockerfile: base/Dockerfile
    hostname: dask-scheduler
    volumes:
      - ./temp:/temp
    ports:
      - "8786:8786"
      - "8787:8787"
  worker_one:
    build:
      context: .
      dockerfile: base/Dockerfile
    hostname: dask-worker
    ports:
      - "8789:8789"
    command: ["bash", "-c", "/usr/bin/prepare.sh && exec dask-worker scheduler:8786"]
    volumes:
      - ./temp:/temp
  notebook:
    build:
      context: .
      dockerfile: notebook/Dockerfile
    hostname: notebook
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
      - ./temp:/temp
      - ./results:/results
  api:
    build:
      context: .
      dockerfile: base/Dockerfile
    hostname: api
    ports:
      - "9001:8888"
    command: ["bash", "-c", "jupyter kernelgateway --KernelGatewayApp.api=notebook-http --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.seed_uri='/home/jovyan/work/api.ipynb'"]
    volumes:
      - ./work:/home/jovyan/work
      - ./temp:/temp
      - ./results:/results
    
