version: '3.1'

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-scheduler
    volumes:
      - ./temp:/temp
    ports:
      - "8786:8786"
      - "8787:8787"
  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker
    ports:
      - "8789:8789"
    command: ["bash", "-c", "/usr/bin/prepare.sh && exec dask-worker scheduler:8786"]
    volumes:
      - ./temp:/temp
  notebook:
    build:
      context: .
      dockerfile: notebook/Dockerfile
    image: daskdev/base-notebook
    hostname: notebook
    ports:
      - "8889:8888"
    volumes:
      - .:/home/jovyan
      - ./temp:/temp
